[project]
name = "personallibrary"
version = "0.0.1"
description = "A basic book library manager built with Flask."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"